<?php

return array(
	'sourceLanguage'=>'zh_cn',
  'import'=>array(
    'modules\\admin\\AdminModule',  
  ),
  'components'=>array(
  	'messages'=>array(
  		'language'=>'en_us',
 	 ),
     'db'=>array(
             'connectionString'=>'mysql:dbname=apidoc;host=127.0.0.1',
             'username'=>'root',
             'password'=>'benben',
             'tablePrefix'=>'apidoc_'
     ),
     'log'=>array(
                'routers'=>array(
                    array('class'=>'benben\log\WebLogRouter') 
                ),
     ),
     'user'=>array(
             'loginUrl'=>array('account/login')
     ),
  	 'assetManager'=>array(
     	'basePath'=>dirname(APPLICATION_PATH).'/public/assets',	
     ),
  ),
  'modules'=>array(
     'admin',
  ),
  'assetsUrl'=>'public',
);
